services:
  - type: web
    name: login-app
    env: node
    plan: free
    buildCommand: cd Backend && npm install && cd ../Frontend && npm install && npm run build
    startCommand: cd Backend && node server.js
    rootDir: .
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri-here
      - key: JWT_SECRET
        value: your-secret-key-here
